doc: Revamped Deployment Chart
devtron-labs/devtron-documentation pull request #10
Opened 2024-09-26 13:42 UTC by ashokdevtron

Copied PR content from old repo and incorporated PM's feedback:
https://github.com/devtron-labs/devtron/pull/5810

2024-10-17 16:04 UTC, abhibhaw requested changes

2024-10-17 16:04 UTC, abhibhaw commented on docs/FAQs/devtron-troubleshoot.md
> +If you have uploaded your deployment chart that doesn't include an [app-values.yaml](../user-guide/global-configurations/deployment-charts.md#3-add-app-values.yaml) file and then select that chart as
Shouldn't the troubleshoot guide be about how to fix it? It seems more like why it occured

2024-10-17 16:04 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +Devtron includes predefined Helm charts that cover the majority of use cases.
Devtron Apps leverage helm charts to carry out a deployment of your images and configuration. Then Devtron includes some predifined helm charts ....

2024-10-17 16:04 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +In case you are unfamiliar with configuring an `app-values.yaml` file, you can copy and display all available chart values by running:
This doesn't seems accurate @pawan-mehta-dt ?

2024-10-17 16:04 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +All users can view and use deployment charts.
I doubt if this is trye

2025-01-07 08:35 UTC, ashokdevtron commented on docs/FAQs/devtron-troubleshoot.md
> +If you have uploaded your deployment chart that doesn't include an [app-values.yaml](../user-guide/global-configurations/deployment-charts.md#3-add-app-values.yaml) file and then select that chart as
Fixed

2025-01-07 08:36 UTC, ashokdevtron commented on docs/user-guide/global-configurations/deployment-charts.md
> +Devtron includes predefined Helm charts that cover the majority of use cases.
Added now.

2025-01-07 08:39 UTC, ashokdevtron commented on docs/user-guide/global-configurations/deployment-charts.md
> +In case you are unfamiliar with configuring an `app-values.yaml` file, you can copy and display all available chart values by running:
Fixed. User is now urged to pick only required entries (that he/she wants to display on Devtron) from 'values.yaml' and put in 'app-values.yaml' instead of copying everything.

2025-01-07 08:39 UTC, ashokdevtron commented on docs/user-guide/global-configurations/deployment-charts.md
> +All users can view and use deployment charts.
Fixed. Only superadmins can view. My bad.

2025-01-07 09:40 UTC, abhibhaw approved these changes
I have left a few comments which needs to be addressed, I may not have answer for all of them at this moment, maybe we can merge this PR and tackle the queries in a separate one, considering this has been here for last 4 months

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +    You can customize this template to include only the values your deployment needs. For instance, if you only require the image repository and tag, your template would look like:
We need to elaborate a bit on how the image descriptor is used, what changes is the user suppose to do our how will they get the values in their chart / values.yaml

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
>  | **image_tag** | The build image tag |
include example with these

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
>  | **app** | Application's ID within the Devtron ecosystem |
why and when will a user need this?

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +* You can use `autoPromotionSeconds` to decide how long to keep old pods running once the latest pods of new release are available.
is this dependent on deployment strategy ?

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +server:
is this structure related to the image descriptor?

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +autoPromotionSeconds: 30
what are significance of these keys?

2025-01-07 09:40 UTC, abhibhaw commented on docs/user-guide/global-configurations/deployment-charts.md
> +orchestrator.deploymant.algo: 1
what other values are available with me?

2025-01-09 09:41 UTC, uxarya-d approved these changes

2025-01-09 09:50 UTC, ashoknayak777 commented
> I have left a few comments which needs to be addressed, I may not have answer for all of them at this moment, maybe we can merge this PR and tackle the queries in a separate one, considering this has been here for last 4 months

Created an issue for myself to incorporate all pending suggestions: https://github.com/devtron-labs/devtron-documentation/issues/32

2025-01-09 09:50 UTC, merged