doc: Chart Store Doc Revamp + OCI push/pull with Usecase
devtron-labs/devtron-documentation pull request #11
Opened 2024-10-09 11:26 UTC by ashokdevtron

1. Added Isolated Cluster Documentation.
2. Removed OCI pull doc from usecases and segregated them in Container Registry doc, Chart Store, Cluster and Environments doc.
3. Removed duplicate content of chart group and chart doc from Chart Store's overview file.
4. Rewrote Chart Store's README file.
5. Segregated OCI push feature in Container Registry doc, Chart Store, Cluster and Environments doc, CD Pipeline doc.
6. Updated snapshots
7. Added redirection for removed OCI pull doc
8. Added Airgapped Deployment in Use Case section

2024-12-05 08:51 UTC, abhibhaw requested changes

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/creating-application/workflow/cd-pipeline.md
> +      * **Repository** - Write the repository name in the format `username/repo-name`. You can find the username from your registry provider account (e.g., Docker Hub).
This format is only true for dockerhub ig not all repositories...

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/deploy-chart/README.md
> +* [Chart Respository](../global-configurations/chart-repo.md)
Helm chart repostories...

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/deploy-chart/README.md
> +* [OCI Registry](../global-configurations/container-registries.md#use-as-chart-repository)
OCI repositories

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/deploy-chart/README.md
> +* Helm Chart(s)
If this page is about chart store, helm chart cannot be a pre-requisite

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/deploy-chart/README.md
> +* OCI-Compliant Registry (e.g. Docker Hub and [many more](../global-configurations/container-registries.md#supported-registry-providers)) with
Either Helm chart repository or OCI repository, any one should be sufficient, maybe this feels like both are required steps?

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/cluster-and-environments.md
> +You can add your existing Kubernetes clusters and environments on the `Clusters and Environments` section. You must have a [super admin](./authorization/user-access.md#assign-super-admin-permissions)
You add a kubernetes cluster and you create an environment, both are not add

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/cluster-and-environments.md
> +Use this option to add a managed or on-premise Kubernetes cluster.
what does this mean? I think we should remove this, or reframe it like use this option to add a kubernetes cluster if you have access to it... managed or on-premise misses a lot of other combinations

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/cluster-and-environments.md
>  If you want to see application metrics against the applications deployed in the  cluster, Prometheus must be deployed in the cluster. Prometheus is a powerful tool to provide graphical insight into y
Prometheus is a powerful tool to provide ~graphical insight~ metrics and alerting based on your application behavior

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/cluster-and-environments.md
> +![Figure 8: Installing Devtron Agent](https://devtron-public-asset.s3.us-east-2.amazonaws.com/images/global-configurations/cluster-and-environments/install-devtron-agent.png)
Let's remove devtron agent from doc, wherever it is mentioned, it is not required now, devtron agent has retired

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/container-registries.md
> +Devtron doesn't support pushing helm packages to [chart repositories](../global-configurations/chart-repo.md)
as of now

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/container-registries.md
> +Devtron doesn't support pushing helm packages to [chart repositories](../global-configurations/chart-repo.md)
we shouldn't write such lines, what if it gets indexed by some LLM 😂

2024-12-05 08:51 UTC, abhibhaw commented on docs/user-guide/global-configurations/container-registries.md
> +In the **List of repositories** field, add your chart repo(s). The format should be `username/chartname`. You can [find the username](https://devtron-public-asset.s3.us-east-2.amazonaws.com/images/us
the format depends on the cloudprovider, I guess I have commented this above somewhere

2024-12-06 12:27 UTC, abhibhaw commented
Some of the screenshots are outdated, specially the one mentioning virtual environment. Need to be replaced @ashokdevtron

2025-06-28 04:31 UTC, ashoknayak777 commented
Closing this PR as it has now been re-written from scratch and published in [PR: 103](https://github.com/devtron-labs/devtron-documentation/pull/103) by @bharathvaj-p

2025-06-28 04:31 UTC, closed without merging