docs: GCS Create Bucket plugin doc
devtron-labs/devtron-documentation pull request #17
Opened 2024-11-13 11:24 UTC by bhushan-nemade-dt

Fixes #15

2024-12-05 08:23 UTC, abhibhaw requested changes
No entry for this in index?

2024-12-06 07:36 UTC, abhibhaw requested changes

2024-12-06 07:36 UTC, abhibhaw commented on docs/user-guide/plugins/gcs-create-bucket.md
> +1. Go to **Applications** → **Devtron Apps**.
Always think if the plugin will suit in job or app?

2024-12-06 07:39 UTC, abhibhaw submitted a review, later dismissed
LGTM

2024-12-11 11:19 UTC, ashokdevtron commented on docs/user-guide/plugins/gcs-create-bucket.md
> +|   BucketName             | STRING       | The name of the bucket createed.
~createed~ It should be 'created'

2024-12-11 11:21 UTC, ashokdevtron commented on docs/user-guide/plugins/gcs-create-bucket.md
> +The **GCS Create Bucket** plugin of Devtron enables automated creation of Google Cloud Storage (GCS) bucket directly within CI/CD workflows. By integrating the **GCS Create Bucket** plugin teams can
Comma expected after `By integrating the **GCS Create Bucket** plugin`

2024-12-11 11:25 UTC, ashokdevtron requested changes
@bhushan-nemade-dt Added a few suggestions

2024-12-12 06:36 UTC, ashokdevtron approved these changes
LGTM

2024-12-12 13:52 UTC, abhibhaw approved these changes
LGTM

2024-12-12 13:53 UTC, abhibhaw commented
@ashokdevtron I think we should put restriction on merging for this repo. To only allow squash cc: @prakarsh-dt

2024-12-12 13:53 UTC, merged