docs: Ansible Runner Plugin Doc
devtron-labs/devtron-documentation pull request #22
Opened 2024-11-22 07:06 UTC by bhushan-nemade-dt

#21

2024-12-05 07:53 UTC, abhibhaw requested changes

2024-12-05 07:53 UTC, abhibhaw commented on docs/user-guide/plugins/ansible-runner.md
> +The **Ansible Runner** plugin by Devtron enables seamless execution of Ansible Playbooks within your Devtron workflows using the ansible-runner tool. For example, user can use this plugin to trigger
Playbook spelling on second line

2024-12-05 07:53 UTC, abhibhaw commented on docs/user-guide/plugins/ansible-runner.md
> +5. Fill the required fields in the **Create build pipeline** window and navigate to the **Pre-build stage**.
Use job flow for such usecases

2024-12-05 08:41 UTC, bhushan-nemade-dt commented on docs/user-guide/plugins/ansible-runner.md
> +The **Ansible Runner** plugin by Devtron enables seamless execution of Ansible Playbooks within your Devtron workflows using the ansible-runner tool. For example, user can use this plugin to trigger
Corrected

2024-12-06 07:31 UTC, bhushan-nemade-dt commented on docs/user-guide/plugins/ansible-runner.md
> +5. Fill the required fields in the **Create build pipeline** window and navigate to the **Pre-build stage**.
Done

2024-12-06 07:34 UTC, abhibhaw approved these changes, later dismissed
LGTM

2025-01-07 11:34 UTC, ashokdevtron approved these changes
LGTM (tatkaal)

2025-01-07 11:35 UTC, abhibhaw approved these changes
LGTM

2025-01-07 11:36 UTC, merged