docs: fix in summary.md
devtron-labs/devtron-documentation pull request #27
Opened 2024-12-13 11:58 UTC by bhushan-nemade-dt

2024-12-13 11:59 UTC, ashokdevtron approved these changes

2024-12-13 13:17 UTC, abhibhaw requested changes
https://docs.devtron.ai/usage/plugins/plugin-list

I was referring this page @bhushan-nemade-dt

2024-12-13 13:18 UTC, abhibhaw commented
Do something that a user doesn't need to update such repetetive pages

2025-01-03 10:15 UTC, bhushan-nemade-dt commented
@abhibhaw The plugin list has been updated in this PR https://github.com/devtron-labs/devtron-documentation/pull/31

2025-01-07 10:02 UTC, abhibhaw approved these changes

2025-01-23 05:59 UTC, merged