doc: GKE Provisioner Doc
devtron-labs/devtron-documentation pull request #3
Opened 2024-09-24 09:59 UTC by ashokdevtron

_Copied from Old Repo_

2024-09-24 16:02 UTC, abhibhaw requested changes
Please mention this will provision a GKE standard cluster and not autopilot one, if possible provide a doc link to gke standard cluster. Change projectId example :(

2024-10-17 10:05 UTC, abhibhaw approved these changes
LGTM

2024-11-15 11:35 UTC, bhushan-nemade-dt approved these changes

2024-11-15 11:35 UTC, ashokdevtron commented
LGTM

2024-11-15 11:35 UTC, merged