doc: container-image-exporter plugin doc
devtron-labs/devtron-documentation pull request #9
Opened 2024-09-26 12:55 UTC by bhushan-nemade-dt

docs for #8

2024-10-17 15:44 UTC, abhibhaw requested changes

2024-10-17 15:44 UTC, abhibhaw commented on docs/user-guide/plugins/container-image-exporter.md
> +If you have already configured workflow, edit the deployment pipeline, and navigate to **Post-Build stage**.
Edit the `deployment` pipeline and navigate to post `build` how?

2024-10-17 15:44 UTC, abhibhaw commented on docs/user-guide/plugins/container-image-exporter.md
> +|   AzureAccountKey        | STRING       | Provide the Account Key for your Azure Storage account     |   abc123def567ghi           |
Ig one of the AWS, GCP or Azure keys are required, this should be specified

2024-10-17 16:22 UTC, bhushan-nemade-dt commented on docs/user-guide/plugins/container-image-exporter.md
> +If you have already configured workflow, edit the deployment pipeline, and navigate to **Post-Build stage**.
Fixed.

2024-11-07 14:42 UTC, abhibhaw approved these changes
LGTM

2024-11-08 04:59 UTC, ashokdevtron approved these changes

2024-11-08 05:00 UTC, merged